# -*- coding: utf-8 -*-
"""29JUN_folium_02.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/183hAzkz-GU543evOiIEk_Bs2RjwePkMC
"""

import folium
from folium import plugins
import numpy as np
import os
import json

icon_plane = plugins.BeautifyIcon(
    icon='plane',
    border_color='#b3334f',
    text_color='#b3334f',
    icon_shape='triangle')

sa_map = folium.Map(location=[29.422918424007776, -98.49499283929646], zoom_start=10)
# ==================== Place ================================
folium.Marker([29.62687992448495, -98.60508003849625], 
              popup = 'Six Flags Fiesta Texas',
              icon = folium.Icon(color='green', icon="star")
              ).add_to(sa_map) # Six Flags Fiesta Texas
folium.Marker([29.475159575145216, -98.69571724663102], 
              popup = 'Sea World San Antonio',
              icon = folium.Icon(color='green', icon="star")
              ).add_to(sa_map) # Sea World San Antonio
folium.Marker([29.434355468891386, -98.43845643091932], 
              popup = 'AT&T Center',
              icon = folium.Icon(color='green', icon="star")
              ).add_to(sa_map) # AT&T Center
folium.Marker([29.424601961345886, -98.48892887744165], 
              popup = 'San Antonio River Walk',
              icon = folium.Icon(color='green', icon="star")
              ).add_to(sa_map) # San Antonio River Walk
folium.Marker([29.442415287373198, -98.47989266771772], 
              popup = 'The Pearl',
              icon = folium.Icon(color='green', icon="star")
              ).add_to(sa_map) # The Pearl
folium.Marker([29.462501093404867, -98.47375412643264], 
              popup = 'San Antonio Zoo',
              icon = folium.Icon(color='green', icon="star")
              ).add_to(sa_map) # San Antonio Zoo

              
# ==================== Historocal Place ================================
folium.Marker([29.42650634344553, -98.4860552640439], 
              popup = 'The Alamo',
              icon = folium.Icon(color='red', icon="info-sign")
              ).add_to(sa_map) # The Alamo

folium.Marker([29.33996408004252, -98.4551864465552], 
              popup = 'Mission San Juan',
              icon = folium.Icon(color='red', icon="info-sign")
              ).add_to(sa_map) # Mission San Juan

folium.Marker([29.36969669472016, -98.48136593244934], 
              popup = 'Mission San Jose Church',
              icon = folium.Icon(color='red', icon="info-sign")
              ).add_to(sa_map) # Mission San Jose Church
# ==================== Food ================================
folium.Marker([29.382694102468434, -98.40482967160935], 
              tooltip = '2M Smokehouse',
              icon = folium.Icon(color='purple', icon="ok") 
              ).add_to(sa_map) # 2M Smokehouse
folium.Marker([29.61053732221805, -98.59893081059525], 
              tooltip = 'Hopdoddy Burger Bar',
              icon = folium.Icon(color='purple', icon="ok") 
              ).add_to(sa_map) # Hopdoddy Burger Bar
folium.Marker([29.444404322943864, -98.48085086103013], 
              tooltip = 'La Gloria',
              icon = folium.Icon(color='purple', icon="ok") 
              ).add_to(sa_map) # La Gloria
folium.Marker([29.47435312186337, -98.67351397579607], 
              tooltip = "Rudy's Bar-B-Q",
              icon = folium.Icon(color='purple', icon="ok") 
              ).add_to(sa_map) # Rudy's "Country Store" and Bar-B-Q
# ==================== Airport ================================
folium.Marker(location=[29.3390683,-98.4700689],
              tooltip = 'Stinson Municipal Airport',
              icon = folium.Icon(color='black', icon="plane") 
              ).add_to(sa_map) # Stinson Municipal Airport
folium.Marker(location=[29.535085325846836, -98.46745911045349],
              tooltip = 'San Antonio International Airport',
              icon = folium.Icon(color='black', icon="plane") 
              ).add_to(sa_map) # San Antonio International Airport
folium.Marker(location=[29.387495143456167, -98.61547028141484],
              tooltip = 'Lackland AFB',
              icon = folium.Icon(color='black', icon="plane") 
              ).add_to(sa_map) # Lackland AFB
folium.Marker(location=[29.524877012087522, -98.28206464643614],
              tooltip = 'Randolph AFB',
              icon = folium.Icon(color='black', icon="plane") 
              ).add_to(sa_map) # Randolph AFB

# ==================== Historic Discricts of San Antonio ================================
with open('/content/drive/MyDrive/Colab Notebooks/Historic_Districts.geojson',mode='rt',encoding='utf-8') as f:
  geo = json.loads(f.read())
  f.close()
folium.GeoJson(
  geo,  
  name='Historic_Districts_of_San_Antonio',
).add_to(sa_map)

sa_map

sa_map.save('/content/drive/MyDrive/Colab Notebooks/sa_map.html')
sa_map

